Description	Resource	Path	Location	Type
exception during macro expansion:   java.lang.NullPointerException 	at scala.collection.immutable.StringOps$.slice$extension(StringOps.scala:41) 	at scala.collection.immutable.StringOps.slice(StringOps.scala:30) 	at scala.collection.IndexedSeqOptimized$class.take(IndexedSeqOptimized.scala:138) 	at scala.collection.immutable.StringOps.take(StringOps.scala:30) 	at org.scalaide.core.resources.MarkerFactory.update(MarkerFactory.scala:61) 	at org.scalaide.core.resources.MarkerFactory.create(MarkerFactory.scala:50) 	at org.scalaide.core.internal.builder.zinc.SbtBuildReporter$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtBuildReporter.scala:88) 	at org.scalaide.core.internal.builder.zinc.SbtBuildReporter$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtBuildReporter.scala:85) 	at scala.Option.map(Option.scala:146) 	at org.scalaide.core.internal.builder.zinc.SbtBuildReporter$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(SbtBuildReporter.scala:85) 	at org.scalaide.core.internal.builder.zinc.SbtBuildReporter$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(SbtBuildReporter.scala:84) 	at scala.Option.flatMap(Option.scala:171) 	at org.scalaide.core.internal.builder.zinc.SbtBuildReporter$$anonfun$1$$anonfun$apply$1.apply(SbtBuildReporter.scala:84) 	at org.scalaide.core.internal.builder.zinc.SbtBuildReporter$$anonfun$1$$anonfun$apply$1.apply(SbtBuildReporter.scala:83) 	at scala.Option.flatMap(Option.scala:171) 	at org.scalaide.core.internal.builder.zinc.SbtBuildReporter$$anonfun$1.apply(SbtBuildReporter.scala:83) 	at org.scalaide.core.internal.builder.zinc.SbtBuildReporter$$anonfun$1.apply(SbtBuildReporter.scala:82) 	at scala.Option.flatMap(Option.scala:171) 	at org.scalaide.core.internal.builder.zinc.SbtBuildReporter.createMarker(SbtBuildReporter.scala:82) 	at org.scalaide.core.internal.builder.zinc.SbtBuildReporter.log(SbtBuildReporter.scala:59) 	at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:39) 	at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:17) 	at scala.reflect.internal.Reporter.warning(Reporting.scala:81) 	at scala.tools.nsc.typechecker.Contexts$ContextReporter.handleWarning(Contexts.scala:1246) 	at scala.tools.nsc.typechecker.Contexts$ContextReporter.info0(Contexts.scala:1287) 	at scala.tools.nsc.typechecker.Contexts$ContextReporter.info0(Contexts.scala:1238) 	at scala.reflect.internal.Reporter.warning(Reporting.scala:81) 	at scala.tools.nsc.typechecker.Contexts$Context.warning(Contexts.scala:579) 	at scala.reflect.macros.contexts.FrontEnds$class.warning(FrontEnds.scala:17) 	at scala.reflect.macros.contexts.Context.warning(Context.scala:6) 	at scala.reflect.macros.contexts.Context.warning(Context.scala:6) 	at macroHost.ParboiledMacro$.assertImpl(ParboiledMacro.scala:49) 	Main.scala	/macroClient/src/macroClient	line 31	Scala Problem
